name: Lint Workflows

on:
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/**"
      - ".github/workflows/*.yaml"
      - ".github/workflows/*.yml"
  workflow_dispatch:

jobs:
  actionlint:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Run actionlint
        uses: raven-actions/actionlint@d3490de4e3f7a2c81f0871bdeb2d9a3ce0c023d8 # v3