import { Context } from "hono";

const STATE_TTL_MS = 10 * 60 * 1000; // 10 minutes

interface OAuthState {
  clientID: string;
  expires: number; // epoch ms
}

/**
 * Verify an OAuth state from KV. Returns true if the state exists,
 * matches the clientID, and is not expired. Deletes the state after
 * verification (one-time use).
 */
export const verifyOAuthState = async (
  c: Context,
  state: string,
  clientID: string
): Promise<boolean> => {
  if (!c.env.KV || !state) return false;
  try {
    const raw = await c.env.KV.get(`oauth_state:${state}`);
    if (!raw) return false;
    const data = JSON.parse(raw) as OAuthState;
    if (data.clientID !== clientID) return false;
    if (Date.now() > data.expires) return false;
    // One-time use: delete after verification
    await c.env.KV.delete(`oauth_state:${state}`);
    return true;
  } catch {
    return false;
  }
};

/**
 * Store an OAuth state in KV. The state is generated by the caller
 * (from the frontend's query param). Returns true on success.
 */
export const storeOAuthState = async (
  c: Context,
  state: string,
  clientID: string
): Promise<boolean> => {
  if (!c.env.KV || !state) return false;
  try {
    const data: OAuthState = {
      clientID,
      expires: Date.now() + STATE_TTL_MS,
    };
    // TTL slightly beyond the expiry for safety
    const ttlSec = Math.ceil(STATE_TTL_MS / 1000) + 30;
    await c.env.KV.put(`oauth_state:${state}`, JSON.stringify(data), {
      expirationTtl: ttlSec,
    });
    return true;
  } catch {
    return false;
  }
};